### ISSUE TITLE
Ulepszenie: informacje w dymkach o przeprowadzonej operacji

### ISSUE THREAD

**Issue by maraf24** [praszuk/josm-plbuildings-plugin#2]
Chciałbym zaproponować dodanie wyświetleń w postaci dymku - dokładnie takim jak na obrazku 
![image](https://user-images.githubusercontent.com/10471006/189547028-7df8885c-39eb-4510-ba98-cbb3d4e3f176.png)

informacji, gdy uruchomiona akcja nie wywołała skutku. Np.
1. budynek nie wymagał aktualizacji (to co w OSM jest identyczne jak w BDOT)
2. budynku nie było w BDOT

W tej chwili jest tak, że często nie jest łatwo się zorientować, czy zaszły zmiany, nie zaszły, czy też jest wydłużone oczekiwanie na dane i zmiany za chwilę będą.

**Comment by praszuk** [comment]
Zaktualizuj proszę plugin :)
Dzisiaj wyszła dość spora [aktualizacja](https://github.com/praszuk/josm-plbuildings-plugin/releases/tag/v1.8.0), która akurat zawiera GUI ze statusami i w zasadzie odpowiada na twoje oba punkty.

**Comment by maraf24** [comment]
Dzięki. Z panelem pracuje się o wiele wygodniej i przyjemniej i prawidłowo pokazuje brak danych w BDOT lub oczekiwanie na ściągnięcie danych.

Upierałbym się jednak, że dodatkowe wyświetlanie dymka w sytuacji "No data" byloby przydatne. 
Czasem korzystam z pluginu sporadycznie, by zaktualizować jeden budynek. W takiej sytuacji nie będę włączał panelu, jednakże w przypadku braku danych chciałbym być o tym poinformowany.

**Comment by praszuk** [comment]
Dodane w wersji [v2.0.0](https://github.com/praszuk/josm-plbuildings-plugin/releases/tag/v2.0.0)
